### ISSUE TITLE
Selectable minecraft version?

### ISSUE THREAD

**Issue by KenJusticeJr** [kitematic/minecraft#18]
Is there a way in your kitematic image to select which minecraft version that you want to run on? 1.11.2 has the mods that my kids want to run.

Thank you!

**Comment by FrenchBen** [comment]
we don't but it should be pretty easy for you to simply build it from source, using the dockerfile in this repo. 
You can then push it to your own repository for your kids to use.

![minecraft](https://media.giphy.com/media/139eZBmH1HTyRa/giphy.gif)
