### ISSUE TITLE
Data dir empty

### ISSUE THREAD

**Issue by metrotyranno** [kitematic/minecraft#9]
On export, the data directory is empty? Though the server seems to store its files since a reboot does not wipe it.

**Comment by metrotyranno** [comment]
"Binds": [
                "/c/Users/bvand/Documents/Kitematic/minecraft/data:/data"
            ],

**Comment by FrenchBen** [comment]
Are there any errors in the logs showing that perhaps the server couldn't write to the dir you are showing?

**Comment by metrotyranno** [comment]
No, the server retains its settings such as the world, playerlocations etc.
